name: build_and_test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Compiler
      run: sudo apt-get install -y llvm clang
    - name: build_and_test
      run: make test
